name: seqneighbor_env
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - biopython
  - colorlog
  - faiss-cpu==1.11.0
  - hnswlib==0.7.0
  - ipykernel
  - matplotlib
  - memory_profiler==0.61.0
  - mmh3
  - networkx
  - nbconvert
  - nltk
  - notebook
  - numpy==1.26.4
  - pandas
  - pygraphviz
  - pynndescent==0.5.12
  - pysam==0.22.1
  - python==3.12
  - python-isal
  - requests
  - scanpy==1.10.1
  - scikit-learn==1.5.0
  - scipy
  - xxhash
