name: CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v3

    - name: Set up Conda
      uses: conda-incubator/setup-miniconda@v2
      with:
        environment-file: environment.yml

    - name: Install package
      shell: bash -l {0}
      run: |
        pip install -v .
   
    - name: Test help message
      shell: bash -l {0}
      run: |
        ./entrypoint.sh --help

    - name: Test workflow
      shell: bash -l {0}
      run: |
        ./entrypoint.sh \
            -i test/data/reads.fasta.gz \
            -o test/output/ \
            -k 15 \
            --kmer-sample-fraction 0.05 \
            --seed 602 \
            --kmer-min-multiplicity 2




    